//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Managerment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string USERNAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public string PASS { get; set; }
        public int TYPE { get; set; }
    }
}
