//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Managerment
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public BILL()
        {
            this.BILL_INFO = new HashSet<BILL_INFO>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE_CHECKIN { get; set; }
        public System.DateTime DATE_CHECKOUT { get; set; }
        public int ID_TABLE { get; set; }
        public int STATUS { get; set; }
    
        public virtual TABLE_DRINK TABLE_DRINK { get; set; }
        public virtual ICollection<BILL_INFO> BILL_INFO { get; set; }
    }
}
