CREATE DATABASE COFFEE_MANAGERMENT
GO
USE COFFEE_MANAGERMENT
----
CREATE TABLE TABLE_DRINK
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'BÀN CHƯA ĐẶT TÊN',
	STATUS NVARCHAR(100) DEFAULT N'BÀN TRỐNG'
)
GO
----

CREATE TABLE ACCOUNT
(
	USERNAME NVARCHAR(100) PRIMARY KEY,
	DISPLAYNAME NVARCHAR(100)NOT NULL DEFAULT 'DERE',
	PASS NVARCHAR(100) NOT NULL DEFAULT 0,
	TYPE INT NOT NULL DEFAULT 0
)
GO
---
CREATE TABLE DRINK_CATEGORY
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN'
)
GO
----
CREATE TABLE DRINK
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN',
	ID_CATEGORY INT NOT NULL,
	PRICE FLOAT NOT NULL DEFAULT 0

	FOREIGN KEY (ID_CATEGORY) REFERENCES DBO.DRINK_CATEGORY(ID)
)
GO
-----
CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DATE_CHECKIN DATE NOT NULL DEFAULT GETDATE(),
	DATE_CHECKOUT DATE NOT NULL,
	ID_TABLE INT NOT NULL,
	STATUS INT NOT NULL DEFAULT 0

	FOREIGN KEY (ID_TABLE) REFERENCES DBO.TABLE_DRINK(ID)
)
GO
-----
CREATE TABLE BILL_INFO
(
	ID INT IDENTITY PRIMARY KEY,
	ID_BILL INT NOT NULL,
	ID_DRINK INT NOT NULL,
	COUNT INT NOT NULL DEFAULT 0

	FOREIGN KEY (ID_BILL) REFERENCES DBO.BILL(ID),
	FOREIGN KEY (ID_DRINK) REFERENCES DBO.DRINK(ID)
)
GO

SELECT * FROM ACCOUNT

