//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Managerment
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRINK_CATEGORY
    {
        public DRINK_CATEGORY()
        {
            this.DRINKs = new HashSet<DRINK>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<DRINK> DRINKs { get; set; }
    }
}
