//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Managerment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COFFEE_MANAGERMENTEntities2 : DbContext
    {
        public COFFEE_MANAGERMENTEntities2()
            : base("name=COFFEE_MANAGERMENTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILL_INFO> BILL_INFO { get; set; }
        public virtual DbSet<DRINK> DRINKs { get; set; }
        public virtual DbSet<DRINK_CATEGORY> DRINK_CATEGORY { get; set; }
        public virtual DbSet<TABLE_DRINK> TABLE_DRINK { get; set; }
    }
}
