//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Managerment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_DRINK
    {
        public TABLE_DRINK()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
